const fs = require('fs');

const randomNames = [
    'Epic Adventure',
    'Mystery of the Night',
    'Journey to the Unknown',
    'The Great Escape',
    'Hidden Treasures',
    'Galactic Odyssey',
    'Whispering Winds',
    'Echoes of Time',
    'Silent Shadows',
    'Dawn of Legends',
    'Lost in Space',
    'Underwater Quest',
    'Mountain Expedition',
    'Desert Mirage',
    'Forest Secrets',
    'Urban Legends',
    'Ancient Ruins',
    'Future Visions',
    'Parallel Worlds',
    'Cosmic Journey',
    'Mystic Lands',
    'Haunted Mansion',
    'Pirate’s Cove',
    'Dragon’s Lair',
    'Robot Invasion',
    'Alien Encounter',
    'Time Traveler',
    'Virtual Reality',
    'Cyberpunk City',
    'Fantasy Realm',
    'Superhero Saga',
    'Zombie Apocalypse',
    'Vampire Chronicles',
    'Werewolf Hunt',
    'Ghost Stories',
    'Magic Spells',
    'Space Mission',
    'Treasure Hunt',
    'Wild West',
    'Medieval Times',
];

const randomVideoLinks = [
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
];

const randomAuthors = [
    'John Doe',
    'Jane Smith',
    'Alice Johnson',
    'Bob Brown',
    'Charlie Davis',
    'Emily Evans',
    'Frank Green',
    'Grace Harris',
    'Henry Jackson',
    'Ivy King',
    'Jack Lee',
    'Karen Miller',
    'Larry Nelson',
    "Mona O'Neil",
    'Nina Parker',
    'Oscar Quinn',
    'Paul Roberts',
    'Quincy Scott',
    'Rachel Turner',
    'Sam Wilson',
    'EpicGamer123',
    'TechGuru',
    'TravelLover',
    'FoodieQueen',
    'MusicManiac',
    'FitnessFreak',
    'MovieBuff',
    'BookWorm',
    'NatureFanatic',
    'GadgetGeek',
    'Fashionista',
    'SportsFanatic',
    'ArtLover',
    'HistoryBuff',
    'ScienceNerd',
    'DIYMaster',
    'PetLover',
    'CarEnthusiast',
    'PhotographyPro',
    'GamingLegend',
    'CookingExpert',
    'AdventureSeeker',
    'BeautyGuru',
    'HealthNut',
    'ComedyKing',
    'NewsJunkie',
    'TravelBug',
    'MusicLover',
    'FitnessGuru',
    'MovieCritic',
    'BookAddict',
    'NatureLover',
    'TechSavvy',
    'FashionGuru',
    'SportsFan',
    'ArtFanatic',
    'HistoryGeek',
    'ScienceBuff',
    'DIYExpert',
    'PetFanatic',
    'CarLover',
    'PhotoFanatic',
    'GamingPro',
    'CookingMaster',
    'AdventureLover',
    'BeautyExpert',
    'HealthGuru',
    'ComedyFanatic',
    'NewsFanatic',
];

const randomComments = [
    'Great video!',
    'Loved it!',
    'Very informative.',
    'Amazing content!',
    'Could be better.',
    'Not what I expected.',
    'Fantastic!',
    'Well done!',
    'I learned a lot.',
    'This was helpful.',
    'Keep it up!',
    'Nice work!',
    'Interesting perspective.',
    'Thanks for sharing.',
    'Good job!',
    "I didn't like it.",
    'This is awesome!',
    'Very well explained.',
    'I disagree with this.',
    'Excellent presentation.',
    'This video was incredibly insightful and provided a lot of valuable information. Thank you!',
    'I really enjoyed watching this. The content was well-presented and easy to understand.',
    'Amazing content! I learned so much from this video. Keep up the great work!',
    'This was a fantastic video. The explanations were clear and the examples were very helpful.',
    'I appreciate the effort put into making this video. It was very informative and engaging.',
    'Great job on this video! The information was presented in a way that was easy to follow.',
    'This video exceeded my expectations. The content was thorough and well-explained.',
    'I found this video to be very helpful. The tips and tricks shared were practical and useful.',
    'Excellent presentation! The visuals and explanations were top-notch.',
    'This video was a great resource. I will definitely be referring back to it in the future.',
    'I loved the way this video was structured. It made the information easy to digest.',
    'Thank you for creating this video. It was very informative and well-made.',
    'This was one of the best videos I have seen on this topic. Great job!',
    'I learned a lot from this video. The content was well-researched and presented.',
    'This video was very well done. The information was clear and concise.',
    'I appreciate the detailed explanations in this video. It was very helpful.',
    'This video was a great learning experience. The content was engaging and informative.',
    'I found this video to be very insightful. The information was presented in a clear and concise manner.',
    'Great video! The content was well-organized and easy to follow.',
    'This video was very helpful. The explanations were clear and the examples were relevant.',
    'This video was incredibly insightful and provided a lot of valuable information. Thank you for taking the time to create such detailed content!',
    'I really enjoyed watching this. The content was well-presented and easy to understand. The examples used were very relevant and helped clarify the concepts.',
    'Amazing content! I learned so much from this video. The explanations were clear and concise, and the visuals were very helpful in understanding the material.',
    'This was a fantastic video. The explanations were clear and the examples were very helpful. I appreciate the effort put into making this video so informative.',
    'I appreciate the effort put into making this video. It was very informative and engaging. The presenter did a great job of breaking down complex topics into easy-to-understand segments.',
    'Great job on this video! The information was presented in a way that was easy to follow. The pacing was just right, and the visuals complemented the explanations perfectly.',
    'This video exceeded my expectations. The content was thorough and well-explained. I especially liked the practical examples that were provided, which made the concepts easier to grasp.',
    'I found this video to be very helpful. The tips and tricks shared were practical and useful. I will definitely be applying some of these techniques in my own work.',
    'Excellent presentation! The visuals and explanations were top-notch. The presenter did a great job of keeping the content engaging and informative throughout the video.',
    'This video was a great resource. I will definitely be referring back to it in the future. The information was well-organized and presented in a logical manner.',
    'I loved the way this video was structured. It made the information easy to digest. The step-by-step approach was very effective in explaining the concepts.',
    'Thank you for creating this video. It was very informative and well-made. The presenter did a fantastic job of explaining the material in a clear and concise manner.',
    'This was one of the best videos I have seen on this topic. Great job! The content was well-researched and presented in an engaging way.',
    'I learned a lot from this video. The content was well-researched and presented. The examples used were very relevant and helped clarify the concepts.',
    'This video was very well done. The information was clear and concise. The presenter did a great job of breaking down complex topics into easy-to-understand segments.',
    'I appreciate the detailed explanations in this video. It was very helpful. The presenter did a great job of keeping the content engaging and informative throughout the video.',
    'This video was a great learning experience. The content was engaging and informative. The presenter did a fantastic job of explaining the material in a clear and concise manner.',
    'I found this video to be very insightful. The information was presented in a clear and concise manner. The examples used were very relevant and helped clarify the concepts.',
    'Great video! The content was well-organized and easy to follow. The pacing was just right, and the visuals complemented the explanations perfectly.',
    'This video was very helpful. The explanations were clear and the examples were relevant. I will definitely be applying some of these techniques in my own work.',
];

const videoDescriptions = [
    "This video takes you on an epic journey through the mountains, showcasing breathtaking landscapes and thrilling adventures. You'll witness the beauty of nature in its purest form, from towering peaks to serene valleys. The journey is filled with unexpected challenges and heartwarming moments. Along the way, you'll meet fascinating characters and hear their inspiring stories. The video captures the essence of exploration and the spirit of adventure. It's a visual feast for the eyes, with stunning cinematography and captivating storytelling. The soundtrack perfectly complements the visuals, enhancing the overall experience. Whether you're an avid adventurer or a nature lover, this video will leave you in awe. It's a reminder of the incredible beauty that exists in the world and the importance of preserving it for future generations.",
    "In this thrilling adventure, we delve into the heart of the city, uncovering its hidden gems and vibrant culture. The video takes you on a whirlwind tour of bustling streets, historic landmarks, and lively markets. You'll get a glimpse of the city's rich history and diverse traditions. The journey is filled with exciting encounters and unexpected surprises. From street performers to local artisans, you'll meet a variety of interesting characters. The video captures the energy and dynamism of urban life, with its fast-paced rhythm and constant movement. The cinematography is top-notch, with stunning shots of the city's skyline and iconic landmarks. The soundtrack adds to the excitement, creating a sense of anticipation and adventure. Whether you're a city dweller or a curious traveler, this video will give you a new perspective on urban life.",
    "Discover the secrets of the ancient ruins in this captivating video. The journey takes you through time, exploring the remnants of lost civilizations and their fascinating histories. You'll see majestic temples, crumbling fortresses, and mysterious artifacts. The video is a treasure trove of knowledge, with detailed explanations and intriguing insights. The storytelling is engaging, weaving together historical facts and legends. The visuals are stunning, with breathtaking shots of the ruins and their surroundings. The soundtrack adds to the atmosphere, creating a sense of wonder and mystery. Whether you're a history buff or a curious explorer, this video will transport you to a different era. It's a reminder of the rich cultural heritage that exists in the world and the importance of preserving it for future generations.",
    "This heartwarming story of friendship and courage will touch your heart. The video follows the journey of two friends as they overcome obstacles and support each other through thick and thin. Their bond is tested by various challenges, but their unwavering loyalty and determination see them through. The storytelling is emotional and inspiring, with moments of joy, sorrow, and triumph. The visuals are beautiful, capturing the essence of their journey and the landscapes they traverse. The soundtrack perfectly complements the narrative, enhancing the emotional impact. Whether you're a fan of heartwarming stories or simply looking for inspiration, this video will leave you feeling uplifted. It's a reminder of the power of friendship and the strength of the human spirit.",
    "Explore the mysteries of the deep ocean in this fascinating video. The journey takes you beneath the waves, revealing the wonders of the underwater world. You'll see colorful coral reefs, exotic marine life, and mysterious shipwrecks. The video is a visual feast, with stunning shots of the ocean's depths and its inhabitants. The storytelling is engaging, with detailed explanations and intriguing insights. The soundtrack adds to the atmosphere, creating a sense of wonder and adventure. Whether you're a marine enthusiast or a curious explorer, this video will transport you to a different world. It's a reminder of the incredible diversity of life that exists in the ocean and the importance of preserving it for future generations.",
    "This captivating tale of love and loss will tug at your heartstrings. The video follows the journey of two lovers as they navigate the ups and downs of their relationship. Their story is filled with moments of joy, sorrow, and everything in between. The storytelling is emotional and engaging, with relatable characters and heartfelt moments. The visuals are beautiful, capturing the essence of their journey and the landscapes they traverse. The soundtrack perfectly complements the narrative, enhancing the emotional impact. Whether you're a fan of romantic stories or simply looking for a heartfelt tale, this video will leave you feeling moved. It's a reminder of the complexities of love and the strength of the human spirit.",
    "An action-packed saga of heroes and villains awaits you in this thrilling video. The journey takes you through epic battles, daring rescues, and heroic feats. The storytelling is gripping, with a fast-paced narrative and dynamic characters. The visuals are stunning, with breathtaking shots of the action and the landscapes they traverse. The soundtrack adds to the excitement, creating a sense of anticipation and adventure. Whether you're a fan of action-packed stories or simply looking for an adrenaline rush, this video will keep you on the edge of your seat. It's a reminder of the power of courage and the importance of standing up for what is right.",
    "A fascinating look at the wonders of space awaits you in this captivating video. The journey takes you beyond the Earth's atmosphere, exploring the mysteries of the cosmos. You'll see distant galaxies, nebulae, and celestial phenomena. The video is a visual feast, with stunning shots of the universe and its wonders. The storytelling is engaging, with detailed explanations and intriguing insights. The soundtrack adds to the atmosphere, creating a sense of wonder and awe. Whether you're a space enthusiast or a curious explorer, this video will transport you to a different world. It's a reminder of the vastness of the universe and the importance of exploring it for future generations.",
    "This gripping drama set in a dystopian future will keep you on the edge of your seat. The video follows the journey of a group of survivors as they navigate a world in chaos. Their story is filled with moments of tension, suspense, and unexpected twists. The storytelling is intense and engaging, with dynamic characters and a fast-paced narrative. The visuals are stunning, capturing the essence of their journey and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of urgency and anticipation. Whether you're a fan of dystopian stories or simply looking for a thrilling tale, this video will leave you captivated. It's a reminder of the resilience of the human spirit and the importance of hope in the face of adversity.",
    "A hilarious comedy about everyday life awaits you in this entertaining video. The journey takes you through the ups and downs of daily routines, with moments of humor and relatability. The storytelling is light-hearted and engaging, with relatable characters and funny situations. The visuals are charming, capturing the essence of everyday life and the landscapes they traverse. The soundtrack adds to the humor, creating a sense of fun and enjoyment. Whether you're a fan of comedies or simply looking for a good laugh, this video will leave you in stitches. It's a reminder of the joy and humor that can be found in the simplest of moments.",
    "A documentary on the wildlife of the Amazon awaits you in this fascinating video. The journey takes you deep into the heart of the rainforest, revealing the wonders of its diverse ecosystem. You'll see exotic animals, lush vegetation, and breathtaking landscapes. The video is a visual feast, with stunning shots of the Amazon and its inhabitants. The storytelling is engaging, with detailed explanations and intriguing insights. The soundtrack adds to the atmosphere, creating a sense of wonder and adventure. Whether you're a wildlife enthusiast or a curious explorer, this video will transport you to a different world. It's a reminder of the incredible diversity of life that exists in the Amazon and the importance of preserving it for future generations.",
    "A suspenseful thriller with unexpected twists awaits you in this gripping video. The journey takes you through a series of mysterious events, with moments of tension and intrigue. The storytelling is intense and engaging, with dynamic characters and a fast-paced narrative. The visuals are stunning, capturing the essence of the suspense and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of urgency and anticipation. Whether you're a fan of thrillers or simply looking for a captivating tale, this video will keep you on the edge of your seat. It's a reminder of the power of suspense and the importance of staying vigilant.",
    "A magical journey through a fantasy world awaits you in this enchanting video. The journey takes you through mystical landscapes, with moments of wonder and adventure. The storytelling is captivating, with dynamic characters and a rich narrative. The visuals are stunning, capturing the essence of the fantasy world and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of magic and enchantment. Whether you're a fan of fantasy stories or simply looking for an escape, this video will transport you to a different world. It's a reminder of the power of imagination and the importance of dreaming big.",
    "A historical drama set in medieval times awaits you in this captivating video. The journey takes you through the lives of knights, kings, and commoners, with moments of intrigue and adventure. The storytelling is engaging, with dynamic characters and a rich narrative. The visuals are stunning, capturing the essence of the medieval world and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of history and grandeur. Whether you're a fan of historical dramas or simply looking for an engaging tale, this video will transport you to a different era. It's a reminder of the rich cultural heritage that exists in the world and the importance of preserving it for future generations.",
    "A sci-fi adventure in a distant galaxy awaits you in this thrilling video. The journey takes you through epic battles, daring rescues, and heroic feats. The storytelling is gripping, with a fast-paced narrative and dynamic characters. The visuals are stunning, with breathtaking shots of the galaxy and the landscapes they traverse. The soundtrack adds to the excitement, creating a sense of anticipation and adventure. Whether you're a fan of sci-fi stories or simply looking for an adrenaline rush, this video will keep you on the edge of your seat. It's a reminder of the power of courage and the importance of exploring the unknown.",
    "A romantic comedy with a twist awaits you in this entertaining video. The journey takes you through the ups and downs of a quirky relationship, with moments of humor and heart. The storytelling is light-hearted and engaging, with relatable characters and funny situations. The visuals are charming, capturing the essence of the romance and the landscapes they traverse. The soundtrack adds to the humor, creating a sense of fun and enjoyment. Whether you're a fan of romantic comedies or simply looking for a good laugh, this video will leave you in stitches. It's a reminder of the joy and humor that can be found in love.",
    "A powerful story of survival and resilience awaits you in this inspiring video. The journey takes you through the challenges and triumphs of individuals who have overcome incredible odds. The storytelling is emotional and engaging, with moments of joy, sorrow, and triumph. The visuals are stunning, capturing the essence of their journey and the landscapes they traverse. The soundtrack perfectly complements the narrative, enhancing the emotional impact. Whether you're a fan of inspiring stories or simply looking for motivation, this video will leave you feeling uplifted. It's a reminder of the strength of the human spirit and the importance of perseverance.",
    "A musical extravaganza with stunning performances awaits you in this entertaining video. The journey takes you through a series of captivating musical acts, with moments of joy and excitement. The storytelling is engaging, with dynamic characters and a rich narrative. The visuals are stunning, capturing the essence of the performances and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of magic and enchantment. Whether you're a fan of musicals or simply looking for an entertaining show, this video will transport you to a different world. It's a reminder of the power of music and the importance of artistic expression.",
    "A chilling horror story that will keep you on the edge of your seat awaits you in this gripping video. The journey takes you through a series of terrifying events, with moments of tension and fear. The storytelling is intense and engaging, with dynamic characters and a fast-paced narrative. The visuals are stunning, capturing the essence of the horror and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of urgency and anticipation. Whether you're a fan of horror stories or simply looking for a thrilling tale, this video will leave you captivated. It's a reminder of the power of fear and the importance of staying vigilant.",
    "A heartwarming family film with a positive message awaits you in this delightful video. The journey takes you through the ups and downs of family life, with moments of joy and love. The storytelling is emotional and engaging, with relatable characters and heartfelt moments. The visuals are beautiful, capturing the essence of their journey and the landscapes they traverse. The soundtrack perfectly complements the narrative, enhancing the emotional impact. Whether you're a fan of family films or simply looking for a feel-good story, this video will leave you feeling uplifted. It's a reminder of the importance of family and the strength of the human spirit.",
    "A sports documentary about a legendary athlete awaits you in this inspiring video. The journey takes you through the highs and lows of their career, with moments of triumph and defeat. The storytelling is engaging, with dynamic characters and a rich narrative. The visuals are stunning, capturing the essence of their journey and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of excitement and anticipation. Whether you're a fan of sports documentaries or simply looking for motivation, this video will leave you feeling inspired. It's a reminder of the power of determination and the importance of perseverance.",
    "A biographical film about a famous artist awaits you in this captivating video. The journey takes you through their life and work, with moments of creativity and inspiration. The storytelling is engaging, with dynamic characters and a rich narrative. The visuals are stunning, capturing the essence of their journey and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of wonder and admiration. Whether you're a fan of biographical films or simply looking for inspiration, this video will transport you to a different world. It's a reminder of the power of creativity and the importance of artistic expression.",
    "A mystery that will keep you guessing until the end awaits you in this gripping video. The journey takes you through a series of puzzling events, with moments of tension and intrigue. The storytelling is intense and engaging, with dynamic characters and a fast-paced narrative. The visuals are stunning, capturing the essence of the mystery and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of urgency and anticipation. Whether you're a fan of mysteries or simply looking for a captivating tale, this video will keep you on the edge of your seat. It's a reminder of the power of curiosity and the importance of staying vigilant.",
    "A coming-of-age story about self-discovery awaits you in this inspiring video. The journey takes you through the ups and downs of growing up, with moments of joy, sorrow, and everything in between. The storytelling is emotional and engaging, with relatable characters and heartfelt moments. The visuals are beautiful, capturing the essence of their journey and the landscapes they traverse. The soundtrack perfectly complements the narrative, enhancing the emotional impact. Whether you're a fan of coming-of-age stories or simply looking for inspiration, this video will leave you feeling uplifted. It's a reminder of the importance of self-discovery and the strength of the human spirit.",
    "A fantasy epic with breathtaking visuals awaits you in this enchanting video. The journey takes you through mystical landscapes, with moments of wonder and adventure. The storytelling is captivating, with dynamic characters and a rich narrative. The visuals are stunning, capturing the essence of the fantasy world and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of magic and enchantment. Whether you're a fan of fantasy stories or simply looking for an escape, this video will transport you to a different world. It's a reminder of the power of imagination and the importance of dreaming big.",
    "A war drama that explores the human side of conflict awaits you in this gripping video. The journey takes you through the lives of soldiers and civilians, with moments of tension, sorrow, and hope. The storytelling is intense and engaging, with dynamic characters and a rich narrative. The visuals are stunning, capturing the essence of the conflict and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of urgency and anticipation. Whether you're a fan of war dramas or simply looking for a powerful story, this video will leave you captivated. It's a reminder of the resilience of the human spirit and the importance of peace.",
    "A crime thriller with a complex plot awaits you in this gripping video. The journey takes you through a series of mysterious events, with moments of tension and intrigue. The storytelling is intense and engaging, with dynamic characters and a fast-paced narrative. The visuals are stunning, capturing the essence of the crime and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of urgency and anticipation. Whether you're a fan of crime thrillers or simply looking for a captivating tale, this video will keep you on the edge of your seat. It's a reminder of the power of curiosity and the importance of staying vigilant.",
    "A romantic drama set in a picturesque location awaits you in this captivating video. The journey takes you through the ups and downs of a passionate relationship, with moments of joy, sorrow, and everything in between. The storytelling is emotional and engaging, with relatable characters and heartfelt moments. The visuals are beautiful, capturing the essence of their journey and the landscapes they traverse. The soundtrack perfectly complements the narrative, enhancing the emotional impact. Whether you're a fan of romantic dramas or simply looking for a heartfelt tale, this video will leave you feeling moved. It's a reminder of the complexities of love and the strength of the human spirit.",
    "A science documentary about groundbreaking discoveries awaits you in this fascinating video. The journey takes you through the latest advancements in various fields, with moments of wonder and excitement. The storytelling is engaging, with detailed explanations and intriguing insights. The visuals are stunning, capturing the essence of the discoveries and the landscapes they traverse. The soundtrack adds to the atmosphere, creating a sense of wonder and awe. Whether you're a science enthusiast or a curious explorer, this video will transport you to a different world. It's a reminder of the power of knowledge and the importance of scientific exploration.",
    '',
];

const randomValue = (length) => Math.floor(Math.random() * length);

const getRandomDate = (start, end) => {
    const startDate = new Date(start).getTime();
    const endDate = new Date(end).getTime();
    const randomTime = new Date(
        startDate + Math.random() * (endDate - startDate)
    );

    return randomTime.toISOString().split('T')[0];
};

const getRandomComment = () => {
    return Array.from({ length: randomValue(30) }, (_, index) => {
        const randomAuthor = randomAuthors[randomValue(randomAuthors.length)];
        const randomComment =
            randomComments[randomValue(randomComments.length)];
        const dateAdded = getRandomDate(
            '2020-01-01',
            new Date().toISOString().split('T')[0]
        );

        return {
            id: index + 1,
            author: randomAuthor,
            comment: randomComment,
            dateAdded,
            likes: randomValue(100),
        };
    });
};

// Create 10 random clips
// Simply change the length to create more or less clips
const clips = Array.from({ length: 10 }, (_, index) => ({
    id: index + 1,
    name: randomNames[randomValue(randomNames.length)],
    thumbnail: `https://picsum.photos/500/300?random=${index + 1}`,
    created_at: getRandomDate(
        '1991-11-09',
        new Date().toISOString().split('T')[0]
    ),
    src: randomVideoLinks[randomValue(randomVideoLinks.length)],
    likes: randomValue(100),
    description: videoDescriptions[randomValue(videoDescriptions.length)],
    comments: getRandomComment(),
}));

const data = { clips };

fs.writeFileSync('db.json', JSON.stringify(data, null, 2), 'utf8');
